on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # pin@v2
    - uses: actions/setup-dotnet@6efb2bd78f16e08562660f8246d6bd76adf6281f # pin@v1
    - name: build
      run: dotnet build -c Release
